### ISSUE TITLE
OscScreenGrabLAN.py broken something between reading and saving

### ISSUE THREAD

**Issue by thephantom1492** [RoGeorge/DS1054Z_screen_capture#3] opened 2015-12-10 06:21 UTC
$ python2.7 OscScreenGrabLAN.py png 192.168.14.1
Instrument ID: RIGOL TECHNOLOGIES,DS1104Z,DS1ZAxxxxxxxxx,00.02.00.SP1

Receiving screen capture...
Traceback (most recent call last):
  File "OscScreenGrabLAN.py", line 149, in <module>
    im = Image.open(StringIO.StringIO(buff))
  File "/usr/lib64/python2.7/site-packages/PIL/Image.py", line 2290, in open
    % (filename if filename else fp))
IOError: cannot identify image file <StringIO.StringIO instance at 0x7f60a7e0aea8>

for csv:
Active channels on the display: []
Traceback (most recent call last):
  File "OscScreenGrabLAN.py", line 172, in <module>
    depth = get_memory_depth(tn)
  File "/tmp/DS1054Z_screen_capture-master/Rigol_functions.py", line 27, in get_memory_depth
    return float(mdep)
ValueError: could not convert string to float: 

for bmp:
Receiving screen capture...
Traceback (most recent call last):
  File "OscScreenGrabLAN.py", line 149, in <module>
    im = Image.open(StringIO.StringIO(buff))
  File "/usr/lib64/python2.7/site-packages/PIL/Image.py", line 2290, in open
    % (filename if filename else fp))
IOError: cannot identify image file <StringIO.StringIO instance at 0x7f6983975ea8>

**Comment by RoGeorge** [comment] 2016-08-13 11:57
Could not reproduce. Closed as not reproducible.

Thank you very much for your feedback.

**Closed as completed by RoGeorge** 2016-08-13 11:57 UTC
